version: '3.3'
volumes:          #define volume
  d-wp:
  d-wp-db:

networks:               #create  network
  wordpress-network: 
    driver: bridge

services:              # create services
  
  wordpress:
    image: wordpress
    restart: always
    container_name: c-wordpress
    ports:
      - 80:80
    
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: a@1
      WORDPRESS_DB_NAME: wordpress
    
    volumes:
      - d-wp:/var/www/html  
    
    networks:
      - wordpress-network
#==========================================
  mariadb:
    image: mariadb
    restart: always
    container_name: c-mariadb-wp
    
    environment:
      MYSQL_ROOT_PASSWORD: a@1
      MYSQL_PASSWORD: a@1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress         
    
    volumes:
      - d-wp-db:/var/lib/mysql  
    
    networks:
      - wordpress-network

#end